#!/usr/bin/env python3
"""Generate deterministic fixed-point CDT fixtures for Boolean parameters."""

from __future__ import annotations

import argparse
import hashlib
import json
from decimal import Decimal, ROUND_FLOOR, getcontext
from pathlib import Path


GENERATOR_VERSION = "moontfhe-cdt-v1"
PARAMETERS = (
    ("boolean_110_lwe", "tfhe-rs-boolean-110-reference", 0x625755FE3CAD),
    ("boolean_110_glwe", "tfhe-rs-boolean-110-reference", 0x40039996A),
    ("boolean_128_lwe", "tfhe-rs-boolean-128-reference", 0x389E49B295AE),
    ("boolean_128_glwe", "tfhe-rs-boolean-128-reference", 0x400000000),
)
U64_MAX = (1 << 64) - 1
Q32 = 1 << 32


def generate_cdt(sigma_q32: int) -> tuple[int, list[int]]:
    getcontext().prec = 90
    sigma = Decimal(sigma_q32) / Decimal(Q32)
    tail_bound = int(
        (Decimal(8) * sigma).to_integral_value(rounding="ROUND_CEILING")
    )
    ratio = (-(Decimal(1) / (Decimal(2) * sigma * sigma))).exp()
    ratio_squared = ratio * ratio
    weight = Decimal(1)
    step = ratio
    weights = [weight]
    for _magnitude in range(1, tail_bound + 1):
        weight *= step
        step *= ratio_squared
        weights.append(Decimal(2) * weight)
    total = sum(weights, Decimal(0))
    cumulative = Decimal(0)
    thresholds: list[int] = []
    for weight in weights:
        cumulative += weight
        threshold = int(
            (cumulative * Decimal(U64_MAX) / total).to_integral_value(
                rounding=ROUND_FLOOR
            )
        )
        thresholds.append(min(threshold, U64_MAX))
    thresholds[-1] = U64_MAX
    return tail_bound, thresholds


def fixture_hash(thresholds: list[int]) -> str:
    packed = b"".join(value.to_bytes(8, "little") for value in thresholds)
    return "sha256:" + hashlib.sha256(packed).hexdigest()


def render(root: Path) -> tuple[str, str]:
    functions: list[str] = [
        "// Generated by tools/noise_fixtures/generate_standard_cdt.py; do not edit.\n"
    ]
    metadata = {
        "generator_version": GENERATOR_VERSION,
        "distribution": "discrete_gaussian_absolute_cdt_u64",
        "tail_sigma": 8,
        "fixtures": [],
    }
    for name, parameter_id, sigma_q32 in PARAMETERS:
        tail_bound, full_thresholds = generate_cdt(sigma_q32)
        magnitude_step = 64 if tail_bound > 1000 else 1
        positions = list(range(0, tail_bound, magnitude_step)) + [tail_bound]
        thresholds = [full_thresholds[position] for position in positions]
        digest = fixture_hash(thresholds)
        metadata["fixtures"].append(
            {
                "name": name,
                "parameter_id": parameter_id,
                "sigma_q32": str(sigma_q32),
                "tail_bound": tail_bound,
                "magnitude_step": magnitude_step,
                "entries": len(thresholds),
                "table_hash": digest,
                "generator_version": GENERATOR_VERSION,
            }
        )
        values = []
        for offset in range(0, len(thresholds), 4):
            row = ", ".join(
                f"0x{value:016X}UL" for value in thresholds[offset : offset + 4]
            )
            values.append(f"      {row},")
        functions.extend(
            [
                "///|",
                f"pub fn gaussian_{name}_fixture() -> DiscreteGaussian {{",
                "  {",
                f"    sigma_q32: 0x{sigma_q32:X}UL,",
                f"    tail_bound: {tail_bound},",
                f"    magnitude_step: {magnitude_step},",
                "    cdt: [",
                *values,
                "    ],",
                f'    fixture_hash: "{digest}".to_string(),',
                "  }",
                "}",
                "",
            ]
        )
    source = "\n".join(functions)
    metadata_text = json.dumps(metadata, indent=2, sort_keys=True) + "\n"
    return source, metadata_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    source_path = root / "src/random/standard_gaussian_fixtures.mbt"
    metadata_path = root / "tools/noise_fixtures/standard-cdt.json"
    source, metadata = render(root)
    if args.check:
        if source_path.read_text() != source or metadata_path.read_text() != metadata:
            raise SystemExit("standard CDT fixtures are stale")
    else:
        source_path.write_text(source)
        metadata_path.write_text(metadata)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
