#!/usr/bin/env python3
"""Generate deterministic fixed-point CDT fixtures for Boolean parameters."""

from __future__ import annotations

import argparse
import hashlib
import json
from decimal import Decimal, ROUND_FLOOR, getcontext
from pathlib import Path


GENERATOR_VERSION = "moontfhe-cdt-u128-v2"
PARAMETERS = (
    ("boolean_110_lwe", "tfhe-rs-boolean-110-reference", 0x625755FE3CAD),
    ("boolean_110_glwe", "tfhe-rs-boolean-110-reference", 0x40039996A),
    ("boolean_128_lwe", "tfhe-rs-boolean-128-reference", 0x389E49B295AE),
    ("boolean_128_glwe", "tfhe-rs-boolean-128-reference", 0x400000000),
)
U64_MAX = (1 << 64) - 1
U128_MAX = (1 << 128) - 1
Q32 = 1 << 32
CHUNK_ENTRIES = 4096


def generate_cdt(sigma_q32: int) -> tuple[int, list[int]]:
    getcontext().prec = 180
    sigma = Decimal(sigma_q32) / Decimal(Q32)
    tail_bound = int(
        (Decimal(8) * sigma).to_integral_value(rounding="ROUND_CEILING")
    )
    ratio = (-(Decimal(1) / (Decimal(2) * sigma * sigma))).exp()
    ratio_squared = ratio * ratio
    weight = Decimal(1)
    step = ratio
    weights = [weight]
    for _magnitude in range(1, tail_bound + 1):
        weight *= step
        step *= ratio_squared
        weights.append(Decimal(2) * weight)
    total = sum(weights, Decimal(0))
    cumulative = Decimal(0)
    thresholds: list[int] = []
    for weight in weights:
        cumulative += weight
        threshold = int(
            (cumulative * Decimal(U128_MAX) / total).to_integral_value(
                rounding=ROUND_FLOOR
            )
        )
        thresholds.append(min(threshold, U128_MAX))
    thresholds[-1] = U128_MAX
    return tail_bound, thresholds


def fixture_hash(thresholds: list[int]) -> str:
    packed = b"".join(value.to_bytes(16, "little") for value in thresholds)
    return "sha256:" + hashlib.sha256(packed).hexdigest()


def render(root: Path) -> tuple[str, dict[str, str], str]:
    functions: list[str] = [
        "// Generated by tools/noise_fixtures/generate_standard_cdt.py; do not edit.\n"
    ]
    chunk_sources: dict[str, str] = {}
    metadata = {
        "generator_version": GENERATOR_VERSION,
        "distribution": "discrete_gaussian_absolute_cdt_u128",
        "tail_sigma": 8,
        "chunk_entries": CHUNK_ENTRIES,
        "fixtures": [],
    }
    for name, parameter_id, sigma_q32 in PARAMETERS:
        tail_bound, thresholds = generate_cdt(sigma_q32)
        digest = fixture_hash(thresholds)
        chunks = [
            thresholds[offset : offset + CHUNK_ENTRIES]
            for offset in range(0, len(thresholds), CHUNK_ENTRIES)
        ]
        metadata["fixtures"].append(
            {
                "name": name,
                "parameter_id": parameter_id,
                "sigma_q32": str(sigma_q32),
                "tail_bound": tail_bound,
                "entries": len(thresholds),
                "chunks": len(chunks),
                "threshold_bits": 128,
                "table_hash": digest,
                "generator_version": GENERATOR_VERSION,
            }
        )
        chunk_names = [f"{name}_cdt_chunk_{index:03d}" for index in range(len(chunks))]
        cdt_lines = (
            [f"    cdt_chunks: [{chunk_names[0]}()],"]
            if len(chunk_names) == 1
            else [
                "    cdt_chunks: [",
                *(f"      {chunk_name}()," for chunk_name in chunk_names),
                "    ],",
            ]
        )
        functions.extend(
            [
                "///|",
                f"pub fn gaussian_{name}_fixture() -> DiscreteGaussian {{",
                "  {",
                f"    sigma_q32: 0x{sigma_q32:X}UL,",
                f"    tail_bound: {tail_bound},",
                f"    cdt_length: {len(thresholds)},",
                *cdt_lines,
                f'    fixture_hash: "{digest}".to_string(),',
                "  }",
                "}",
                "",
            ]
        )
        for chunk_index, chunk in enumerate(chunks):
            words = []
            for value in chunk:
                words.extend((value >> 64, value & U64_MAX))
            payload = "".join(f"{value:016X}" for value in words)
            payload_lines = [
                f"      #|{payload[offset : offset + 128]}"
                for offset in range(0, len(payload), 128)
            ]
            chunk_sources[f"standard_cdt_{name}_{chunk_index:03d}.mbt"] = "\n".join(
                [
                    "// Generated by tools/noise_fixtures/generate_standard_cdt.py; do not edit.",
                    "",
                    "///|",
                    f"fn {chunk_names[chunk_index]}() -> FixedArray[UInt64] {{",
                    "  cdt_chunk_from_hex(",
                    "    (",
                    *payload_lines,
                    "    ),",
                    "  )",
                    "}",
                    "",
                ]
            )
    source = "\n".join(functions)
    metadata_text = json.dumps(metadata, indent=2, sort_keys=True) + "\n"
    return source, chunk_sources, metadata_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    source_path = root / "src/random/standard_gaussian_fixtures.mbt"
    metadata_path = root / "tools/noise_fixtures/standard-cdt.json"
    source, chunk_sources, metadata = render(root)
    if args.check:
        expected = {source_path: source, metadata_path: metadata}
        expected.update({source_path.parent / name: text for name, text in chunk_sources.items()})
        if any(not path.exists() or path.read_text() != text for path, text in expected.items()):
            raise SystemExit("standard CDT fixtures are stale")
    else:
        source_path.write_text(source)
        metadata_path.write_text(metadata)
        for stale in source_path.parent.glob("standard_cdt_*.mbt"):
            stale.unlink()
        for name, text in chunk_sources.items():
            (source_path.parent / name).write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
